// This file was auto-generated by ML.NET Model Builder. 

using System;
using ConsoleApp1ML.Model;

namespace ConsoleApp1ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Message = @"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",
                Length = 111F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");
            Console.WriteLine($"Message: {sampleData.Message}");
            Console.WriteLine($"Length: {sampleData.Length}");
            Console.WriteLine($"\n\nPredicted Label value {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
